/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NavBack: typeof import('./components/nav-back/index.vue')['default']
    PageContainer: typeof import('./components/page-container/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlotBack: typeof import('./components/slot-back/index.vue')['default']
  }
}
